print("Storing Birthdays")

name1 = input("Enter Person Name 1: ")
birthday1 = input("Enter birthday: ")
print(name1, "'s birthday is : ", birthday1)

name2 = input("Enter Person Name 2: ")
birthday2 = input("Enter birthday: ")
print(name2, "'s birthday is : ", birthday2)

name3 = input("Enter Person Name 3: ")
birthday3 = input("Enter birthday: ")
print(name3, "'s birthday is : ", birthday3)

name4 = input("Enter Person Name 4: ")
birthday4 = input("Enter birthday: ")
print(name4, "'s birthday is : ", birthday4)

name5 = input("Enter Person Name 5: ")
birthday5 = input("Enter birthday: ")
print(name5, "'s birthday is : ", birthday5)